//! Size and authorization policy for high-volume factory traffic.

use crate::config::Config;

/// Select the message body cap for the requested message kind.
pub(crate) fn message_body_limit(config: &Config, blocker: bool, merge_request: bool) -> usize {
    let factory = config.factory();
    if blocker || merge_request {
        factory.message_max_chars_escalation
    } else {
        factory.message_max_chars
    }
}

/// Return the configured cap for one appended task note.
pub(crate) fn note_body_limit(config: &Config) -> usize {
    config.factory().note_max_chars
}

/// Whether a message was generated by a Cassy lifecycle/director path.
///
/// These sources are already bounded by the lifecycle envelope policy. This
/// exemption is deliberately based on the server-selected source rather than
/// caller-provided message content.
pub(crate) fn source_is_exempt(source: &str) -> bool {
    let source = source.to_ascii_lowercase();
    source.eq_ignore_ascii_case("cas")
        || source.eq_ignore_ascii_case("director")
        || source.starts_with("lifecycle:")
        || source.starts_with("lifecycle-")
}

fn artifact_guidance(task_id: &str) -> String {
    let task_id = task_id.trim();
    let task_id = if task_id.is_empty() {
        "<task-id>"
    } else {
        task_id
    };
    format!(
        "Write the evidence to `[factory] artifacts_root/{task_id}/<name>.md` and send the path plus a one-paragraph summary."
    )
}

fn body_limit_error(kind: &str, limit: usize, actual: usize, task_id: &str) -> String {
    format!(
        "{kind} body rejected: limit is {limit} characters, actual length is {actual}. {}",
        artifact_guidance(task_id)
    )
}

/// Validate an agent-authored message before any routing or queue side effect.
pub(crate) fn validate_message_body(
    source: &str,
    body: &str,
    config: &Config,
    blocker: bool,
    merge_request: bool,
    task_id: &str,
) -> Result<(), String> {
    if source_is_exempt(source) {
        return Ok(());
    }

    let limit = message_body_limit(config, blocker, merge_request);
    let actual = body.chars().count();
    if actual > limit {
        return Err(body_limit_error("Message", limit, actual, task_id));
    }
    Ok(())
}

/// Where an over-cap supervisor message is spilled: the configured
/// `[factory] artifacts_root`, else the documented real-disk fallback
/// `~/.cas/artifacts`. `None` when neither is available.
pub(crate) fn message_spill_root(config: &Config) -> Option<std::path::PathBuf> {
    let configured = config
        .factory()
        .artifacts_root
        .filter(|root| !root.trim().is_empty());
    if configured.is_none() && std::env::var_os("HOME").is_none_or(|home| home.is_empty()) {
        return None;
    }
    Some(crate::config::resolved_factory_artifacts_root(
        configured.as_deref(),
    ))
}

/// A task id is used as a directory name only when it cannot escape the
/// artifacts root; anything else spills under `_messages`.
fn spill_directory_name(task_id: Option<&str>) -> &str {
    task_id
        .map(str::trim)
        .filter(|id| {
            !id.is_empty()
                && !id.starts_with('.')
                && id
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        })
        .unwrap_or("_messages")
}

/// cas-6ee6 (GH #1006 item 1): deliver an over-cap supervisor message
/// instead of refusing it. The full text is written to
/// `<artifacts_root>/<task-id or _messages>/message-<utc>-<hash>.md`, and the
/// returned body — the head of the message plus that path — fits `limit`
/// whenever the pointer itself does; the path is never dropped to make room.
///
/// Errors name why nothing could be spilled: no artifacts root is available,
/// or the file could not be written.
pub(crate) fn spill_message_to_artifact(
    root: Option<&std::path::Path>,
    task_id: Option<&str>,
    sender: &str,
    target: &str,
    summary: &str,
    body: &str,
    limit: usize,
    now: chrono::DateTime<chrono::Utc>,
) -> Result<String, String> {
    use sha2::{Digest, Sha256};

    let actual = body.chars().count();
    let root = root.ok_or_else(|| {
        format!(
            "Message body rejected: limit is {limit} characters, actual length is {actual}, and it could not be spilled to an artifact because no `[factory] artifacts_root` is configured and HOME is unset. Configure artifacts_root, or write the text to a file and send its path plus a one-paragraph summary."
        )
    })?;
    let directory = root.join(spill_directory_name(task_id));
    let digest = Sha256::digest(body.as_bytes());
    let short_hash: String = digest.iter().take(4).map(|byte| format!("{byte:02x}")).collect();
    let path = directory.join(format!(
        "message-{}-{short_hash}.md",
        now.format("%Y%m%dT%H%M%SZ")
    ));
    let document = format!(
        "# Message from {sender} to {target}\n\nSent: {}\nSummary: {summary}\nLength: {actual} characters\n\n---\n\n{body}\n",
        now.to_rfc3339()
    );
    std::fs::create_dir_all(&directory)
        .and_then(|()| std::fs::write(&path, document))
        .map_err(|error| {
            format!(
                "Message body rejected: limit is {limit} characters, actual length is {actual}, and spilling it to {} failed: {error}. Write the text to a file and send its path plus a one-paragraph summary.",
                path.display()
            )
        })?;

    let pointer = format!(
        "\n\n[Message continues: the full {actual}-character text is at {}]",
        path.display()
    );
    let head_budget = limit.saturating_sub(pointer.chars().count() + 1);
    let head: String = body.chars().take(head_budget).collect();
    Ok(format!("{}…{pointer}", head.trim_end()))
}

/// Validate an appended task note and authorize the only supported override.
///
/// The return value records whether a supervisor override was accepted so the
/// caller can include its reason in the durable activity event metadata.
pub(crate) fn validate_note_body(
    note_type: &str,
    body: &str,
    config: &Config,
    task_id: &str,
    supervisor_override: bool,
    registered_supervisor: bool,
    reason: Option<&str>,
) -> Result<bool, String> {
    let note_type = note_type.trim().to_ascii_lowercase();
    if supervisor_override {
        if !registered_supervisor {
            return Err(
                "SUPERVISOR OVERRIDE REJECTED: supervisor_override=true is only available to a registered supervisor."
                    .to_string(),
            );
        }
        if reason.is_none_or(|reason| reason.trim().is_empty()) {
            return Err(
                "SUPERVISOR OVERRIDE REJECTED: a non-empty reason is required and will be logged."
                    .to_string(),
            );
        }
        if !matches!(note_type.as_str(), "discovery" | "decision") {
            return Err(
                "SUPERVISOR OVERRIDE REJECTED: supervisor_override=true is supported only for discovery or decision notes."
                    .to_string(),
            );
        }
        return Ok(true);
    }

    let limit = note_body_limit(config);
    let actual = body.chars().count();
    if actual > limit {
        return Err(body_limit_error("Task note", limit, actual, task_id));
    }
    Ok(false)
}

#[cfg(test)]
mod tests {
    use crate::config::{Config, FactoryConfig};

    use super::{
        message_body_limit, note_body_limit, source_is_exempt, spill_message_to_artifact,
        validate_message_body, validate_note_body,
    };

    fn config_with_limits(message: usize, escalation: usize, note: usize) -> Config {
        let mut factory = FactoryConfig::default();
        factory.message_max_chars = message;
        factory.message_max_chars_escalation = escalation;
        factory.note_max_chars = note;
        Config {
            factory: Some(factory),
            ..Config::default()
        }
    }

    #[test]
    fn message_limit_switches_to_escalation_for_blockers_and_merges() {
        let config = config_with_limits(5, 11, 7);

        assert_eq!(message_body_limit(&config, false, false), 5);
        assert_eq!(message_body_limit(&config, true, false), 11);
        assert_eq!(message_body_limit(&config, false, true), 11);
    }

    #[test]
    fn message_body_accepts_exact_cap_and_rejects_cap_plus_one() {
        let config = config_with_limits(5, 11, 7);

        assert!(
            validate_message_body("worker", "12345", &config, false, false, "cas-449b").is_ok()
        );
        let error = validate_message_body("worker", "123456", &config, false, false, "cas-449b")
            .expect_err("message cap must reject cap + 1");
        assert!(error.contains("limit is 5 characters"), "{error}");
        assert!(error.contains("actual length is 6"), "{error}");
        assert!(
            error.contains("[factory] artifacts_root/cas-449b/<name>.md"),
            "{error}"
        );
        assert!(error.contains("one-paragraph summary"), "{error}");
    }

    #[test]
    fn cas_generated_message_sources_are_exempt() {
        let config = config_with_limits(5, 11, 7);
        let oversized = "123456";

        for source in [
            "cas",
            "lifecycle:task-closed",
            "lifecycle-wake:worker-died",
            "lifecycle-outbox:42",
            "director",
        ] {
            assert!(source_is_exempt(source), "{source}");
            assert!(
                validate_message_body(source, oversized, &config, false, false, "cas-449b").is_ok(),
                "{source} must bypass the agent-authored cap"
            );
        }
    }

    #[test]
    fn note_body_accepts_exact_cap_and_rejects_cap_plus_one() {
        let config = config_with_limits(5, 11, 7);

        assert!(
            validate_note_body(
                "progress", "1234567", &config, "cas-449b", false, false, None
            )
            .is_ok()
        );
        let error = validate_note_body(
            "blocker", "12345678", &config, "cas-449b", false, false, None,
        )
        .expect_err("note cap must reject cap + 1");
        assert!(error.contains("limit is 7 characters"), "{error}");
        assert!(error.contains("actual length is 8"), "{error}");
        assert!(
            error.contains("[factory] artifacts_root/cas-449b/<name>.md"),
            "{error}"
        );
    }

    #[test]
    fn supervisor_override_preserves_long_review_notes_and_requires_reason() {
        let config = config_with_limits(5, 11, 7);
        let long_note = "12345678";

        assert_eq!(
            validate_note_body(
                "discovery",
                long_note,
                &config,
                "cas-449b",
                true,
                true,
                Some("merge receipt review"),
            )
            .expect("registered supervisor may preserve review evidence"),
            true
        );
        let error =
            validate_note_body("decision", long_note, &config, "cas-449b", true, true, None)
                .expect_err("override reason must be mandatory");
        assert!(error.contains("reason"), "{error}");
    }

    #[test]
    fn note_override_rejects_unregistered_callers() {
        let config = config_with_limits(5, 11, 7);
        let error = validate_note_body(
            "decision",
            "12345678",
            &config,
            "cas-449b",
            true,
            false,
            Some("review finding"),
        )
        .expect_err("only a registered supervisor may override");
        assert!(error.contains("registered supervisor"), "{error}");
    }

    /// cas-6ee6 (GH #1006 item 1): a 1,503-character supervisor ruling was
    /// refused at the 1,200 cap. It is now delivered as its head plus the
    /// path of an artifact holding the full text.
    #[test]
    fn over_cap_message_spills_full_text_and_delivers_head_with_path_cas_6ee6() {
        let root = tempfile::tempdir().unwrap();
        let body = format!("RULING: {}", "contract excerpt and decision. ".repeat(50));
        assert!(body.chars().count() > 1_200);
        let now = chrono::DateTime::parse_from_rfc3339("2026-09-24T15:29:00Z")
            .unwrap()
            .with_timezone(&chrono::Utc);

        let delivered = spill_message_to_artifact(
            Some(root.path()),
            Some("cas-6ee6"),
            "noble-heron-32",
            "sturdy-crane-8",
            "ruling",
            &body,
            1_200,
            now,
        )
        .expect("an over-cap supervisor message is delivered, not refused");

        assert!(delivered.chars().count() <= 1_200, "{}", delivered.chars().count());
        assert!(delivered.starts_with("RULING: contract excerpt"), "{delivered}");
        let dir = root.path().join("cas-6ee6");
        let files: Vec<_> = std::fs::read_dir(&dir).unwrap().map(|e| e.unwrap().path()).collect();
        assert_eq!(files.len(), 1);
        let path = &files[0];
        assert!(
            path.file_name().unwrap().to_str().unwrap().starts_with("message-20260924T152900Z-"),
            "{}",
            path.display()
        );
        assert!(delivered.contains(&path.display().to_string()), "{delivered}");
        let stored = std::fs::read_to_string(path).unwrap();
        assert!(stored.contains(&body), "the artifact carries the full text");
        assert!(stored.contains("noble-heron-32") && stored.contains("sturdy-crane-8"));
    }

    #[test]
    fn spill_without_a_task_or_with_an_unsafe_id_uses_messages_directory_cas_6ee6() {
        let root = tempfile::tempdir().unwrap();
        let body = "x".repeat(50);
        for task_id in [None, Some("../escape"), Some("")] {
            spill_message_to_artifact(
                Some(root.path()),
                task_id,
                "sup",
                "worker",
                "s",
                &body,
                10,
                chrono::Utc::now(),
            )
            .unwrap();
        }
        assert!(root.path().join("_messages").is_dir());
        assert!(!root.path().parent().unwrap().join("escape").exists());
    }

    #[test]
    fn spill_refusal_names_the_missing_artifacts_root_cas_6ee6() {
        let error = spill_message_to_artifact(
            None,
            Some("cas-6ee6"),
            "sup",
            "worker",
            "s",
            &"x".repeat(20),
            10,
            chrono::Utc::now(),
        )
        .expect_err("no root means the refusal remains");
        assert!(error.contains("limit is 10 characters"), "{error}");
        assert!(error.contains("no `[factory] artifacts_root` is configured"), "{error}");
    }

    #[test]
    fn configured_note_limit_is_read_from_factory() {
        let config = config_with_limits(5, 11, 7);

        assert_eq!(note_body_limit(&config), 7);
    }
}
