import { createHash, webcrypto } from "node:crypto";
import { readFile } from "node:fs/promises";
import { afterEach, describe, expect, it, vi } from "vitest";
import { HubConnectionSupervisor, type HubCallbacks } from "./connection";
import { createDeviceKey, dpopHeaders } from "./dpop";
import { consumePairingFragment } from "./fragment";
import type { StoredMachine } from "./types";

Object.defineProperty(globalThis, "crypto", { value: webcrypto, configurable: true });

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllGlobals();
});

describe("binding Commander browser invariants", () => {
  it("H4-CATALOG-01 consumes pairing fragments synchronously and preserves no capability in the URL", () => {
    const token = "A".repeat(43);
    let replacement = "";
    const location = { hash: `#pair=${token}&hub=machine-1`, pathname: "/", search: "" } as Location;
    const history = { replaceState: (_: unknown, __: string, path: string) => { replacement = path; } } as unknown as History;
    expect(consumePairingFragment(location, history)).toEqual({ token, hubId: "machine-1" });
    expect(replacement).toBe("/");
    expect(replacement).not.toContain(token);
  });

  it("keeps the legacy Pair action disabled with an explanation while offering page-initiated pairing", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
    expect(source).toContain('pendingPairing ? "" : \'<p class="pairing-disabled-reason">Pair is disabled until you open a pairing URL generated by <code>cas hub pair</code> on the machine.</p>\'');
    expect(source).toContain('<button type="button" ${pendingPairing ? "" : "disabled"}>Pair</button>');
    expect(source).toContain('id="pair-create" type="button" class="primary"');
    expect(source).toContain('pairingCreateInFlight ? "Creating…" : "Create pairing code"');
    expect(source).toContain("const relayAction = relayOrigin");
    expect(html).toContain('name="cas-pairing-relay-origin" content="https://petra-stella-cloud.vercel.app"');
  });

  it("names the remedy when an observer-only credential disables control", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("Relay pairing granted read-only scopes for ${location.origin}");
    expect(source).toContain("cas hub pair --origin ${location.origin}");
    expect(source).toContain("Pairings are specific to each Commander origin.");
    expect(source).toContain('class="control-action" title="${escapeAttr(takeControlReason');
    expect(source).toContain('disabled aria-describedby="control-disabled-reason"');
    expect(source).toContain('class="control-disabled-reason"');
  });

  it("derives the header mode and terminal cursor from the real session lease", async () => {
    const [main, terminal] = await Promise.all([
      readFile(new URL("main.ts", import.meta.url), "utf8"),
      readFile(new URL("terminal/ghostty/surface.ts", import.meta.url), "utf8"),
    ]);
    expect(main).toContain('const mode = lease?.held_by_me ? "CONTROL" : "OBSERVER"');
    expect(main).toContain('class="mode-badge ${mode.toLowerCase()}"');
    expect(main).toContain("setControlMode(leases.get(selectedKey)?.held_by_me === true)");
    expect(terminal).toContain("state.controlMode && state.focused");
  });

  it("renders instructional empty pane and all-clear feed states", async () => {
    const [main, attentionView] = await Promise.all([
      readFile(new URL("main.ts", import.meta.url), "utf8"),
      readFile(new URL("attention-view.ts", import.meta.url), "utf8"),
    ]);
    expect(main).toContain("No session — pick one from the drawer or drag it here.");
    expect(main).toContain('empty.className = "empty empty-pane-slot"');
    expect(attentionView).toContain('message.textContent = "All clear"');
    expect(attentionView).toContain("Last event ${new Date(latest.createdAt).toLocaleString()}");
  });

  it("binds the browser fetch receiver at every pairing handoff", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).not.toMatch(/fetcher:\s*(?:window\.|globalThis\.)?fetch\s*[,}]/);
    expect(source).not.toMatch(/(?:acknowledgePairing|createPairingRequest|pollPairingRequest)\(\s*(?:window\.|globalThis\.)?fetch\s*,/);
  });

  it("H4-STORAGE-02 creates a non-extractable P-256 signing key and valid proof", async () => {
    const { privateKey, publicKey } = await createDeviceKey();
    expect(privateKey.extractable).toBe(false);
    await expect(crypto.subtle.exportKey("jwk", privateKey)).rejects.toThrow();
    const machine = {
      id: "machine", label: "Machine", baseUrl: "https://hub.example", deviceId: "device",
      credentialId: "credential-id", credential: "opaque-credential", expiresAt: new Date(Date.now() + 60_000).toISOString(),
      scopes: ["machine-read"], publicKey, privateKey,
    } satisfies StoredMachine;
    const headers = await dpopHeaders(machine, "GET", "/v1/machine");
    const [encodedHeader, encodedClaims, encodedSignature] = headers.DPoP.split(".");
    const decode = (value: string) => Buffer.from(value, "base64url");
    expect(JSON.parse(decode(encodedClaims).toString())).toMatchObject({ htm: "GET", htu: "/v1/machine" });
    const imported = await crypto.subtle.importKey("jwk", publicKey, { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
    expect(await crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, imported, decode(encodedSignature), new TextEncoder().encode(`${encodedHeader}.${encodedClaims}`))).toBe(true);
  });

  it("pins the green Ghostty WASM spike artifacts by integrity", async () => {
    const cases = [
      ["terminal/ghostty/vendor/ghostty-vt.wasm", "6b1df1a96d59adc26360c312924898dbc122f980c17a32eb1624e48795b83f7e"],
      ["terminal/ghostty/vendor/ghostty-write-pty.wasm", "75cb147e98ede3f85f3cd6236a30f6d12565b0b237e1d8db941f5f3e8ad3d903"],
    ];
    for (const [path, expected] of cases) {
      const bytes = await readFile(new URL(path, import.meta.url));
      expect(createHash("sha256").update(bytes).digest("hex")).toBe(expected);
    }
  });

  it("keeps long-lived credentials out of ambient browser storage and URL channels", async () => {
    const source = await Promise.all(["storage.ts", "dpop.ts"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    const joined = source.join("\n");
    for (const forbidden of ["local" + "Storage", "document.cookie", "serviceWorker.register", "caches.open"]) {
      expect(joined).not.toContain(forbidden);
    }
    expect(await readFile(new URL("storage.ts", import.meta.url), "utf8")).not.toContain("session" + "Storage");
    expect(joined).toContain("indexedDB.open");

    // Layout is an intentionally non-secret, per-device preference. It must
    // remain isolated from the IndexedDB credential catalog.
    const layout = await readFile(new URL("pane-layout.ts", import.meta.url), "utf8");
    expect(layout).toContain("cas-commander:pane-layout:");
    for (const secretField of ["credential", "privateKey", "deviceKey"]) expect(layout).not.toContain(secretField);
  });

  it("feature-detects hub versions and keeps controls disabled on skew", async () => {
    const source = await Promise.all(["main.ts", "connection.ts"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    const joined = source.join("\n");
    expect(joined).toContain('"/v1/machine"');
    expect(joined).toContain("Compatibility check unavailable");
    expect(joined).toContain('hubSupports(machineId, "daemon_attach")');
    expect(joined).toContain("unsupported controls are disabled");
  });

  it("targets interrupt at the explicitly selected pane rather than render order", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("selectedPanes.get(sessionKey(selected.id, selectedSession))");
    expect(source).toContain("{ InterruptPane: { pane_id: pane } }");
    expect(source).not.toContain("[...surfaces.keys()].find");
  });

  it("never caches an asynchronously-created terminal against a detached render", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("existingSurface.element !== mount || !existingSurface.element.isConnected");
    expect(source).toContain("!mount.isConnected || currentMount !== mount");
    expect(source).toContain("surface.dispose();");
  });

  it("preserves the active pane grid across lease and status renders", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("currentGrid?.dataset.sessionKey === terminalSessionKey");
    expect(source).toContain("replaceWith(preservedGrid)");
    expect(source).toContain("data-session-key");
  });

  it("keeps the phone ATTENTION hierarchy human-readable and group-actionable", async () => {
    const [main, attentionView, css] = await Promise.all(["main.ts", "attention-view.ts", "styles.css"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    expect(main).toContain('machineEventAttention(kind, event.diagnostic)');
    expect(main).toContain('renderAttentionPanel(container, attention');
    expect(attentionView).toContain('headline.textContent = card.content.headline');
    expect(attentionView).toContain('button("Dismiss all info"');
    expect(attentionView).toContain('button("Dismiss group"');
    expect(attentionView).toContain('severity !== "critical"');
    expect(css).toContain(".attention-item--critical");
    expect(css).toContain("prefers-reduced-motion: reduce");
    expect(css).toContain("@media (max-width: 53rem)");
    expect(css).toContain("max-width: var(--mobile-attention-label-width)");
  });

  it("keeps the section 2 visual system tokenized and machine copy mono", async () => {
    const [main, css, html, renderer, surface] = await Promise.all([
      "main.ts",
      "styles.css",
      "../index.html",
      "terminal/ghostty/renderer.ts",
      "terminal/ghostty/surface.ts",
    ].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    for (const token of [
      "--bg-root: #101318",
      "--bg-panel: #151922",
      "--bg-raised: #1B202B",
      "--bg-terminal: #0C0E13",
      "--bg-hover: #222836",
      "--bg-active: #2A3142",
      "--line-subtle: #232936",
      "--line-strong: #38415A",
      "--text-hi: #E8EBF2",
      "--text-mid: #9AA3B5",
      "--text-lo: #5C6577",
      "--state-ok: #4CC38A",
      "--state-warn: #E5B454",
      "--state-crit: #E5645E",
      "--state-info: #6CA7F2",
      "--state-idle: #5C6577",
      "--fs-xs: .6875rem",
      "--fs-sm: .78125rem",
      "--fs-base: .84375rem",
      "--fs-md: .9375rem",
      "--fs-lg: 1.125rem",
      "--radius-card: 6px",
      "--radius-pane: 8px",
      "--radius-pill: 999px",
    ]) expect(css).toContain(token);

    const rootEnd = css.indexOf("\n}\n");
    expect(rootEnd).toBeGreaterThan(0);
    const componentCss = css.slice(rootEnd + 3);
    expect(componentCss).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    expect(componentCss).not.toMatch(/rgba?\(/i);
    expect(main).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    expect(html).not.toMatch(/#[0-9a-f]{3,8}\b/i);

    expect(main).toContain('class="session-name"');
    expect(main).toContain('class="session-meta"');
    expect(main).toContain('"toolbar-session-title"');
    expect(main).toContain('span.className = "status-identifier"');
    expect(css).toContain("font-family: var(--font-mono)");
    expect(css).not.toContain("border-right:");
    expect(css).not.toContain(".context { border-left:");
    expect(css.match(/box-shadow:/g)).toHaveLength(2);
    expect(renderer).not.toContain('"700"');
    expect(surface).not.toContain('"normal 700"');
    expect(surface).not.toContain('"italic 700"');
  });

  it("encodes the supervisor-first Commander shell at desktop and phone widths", async () => {
    const [main, css, connection] = await Promise.all(["main.ts", "styles.css", "connection.ts"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    expect(main).toContain('class="machine-navigation${machineDrawerOpen ? " drawer-open" : ""}"');
    expect(main).toContain('id="pair-toggle" class="rail-control pair-machine"');
    expect(main).toContain('class="session-header"');
    expect(main).toContain('data-context-tab="status"');
    expect(main).toContain('Workers &amp; Tasks');
    expect(main).toContain('visiblePanes.find((pane) => pane.kind === "Supervisor")?.id');
    expect(main).toContain('data-machine-latency');
    expect(connection).toContain('onLatency?(latencyMs: number)');
    expect(css).toContain('--machine-rail-width: 48px');
    expect(css).toContain('--context-panel-width: 320px');
    expect(css).toContain('--session-header-height: 44px');
    expect(css).toContain('--pane-header-height: 32px');
    expect(css).toContain('grid-template-columns: var(--machine-rail-width) minmax(0, 1fr) var(--context-panel-width)');
    expect(css).toContain('flex: 0 0 var(--session-header-height)');
    expect(css).toContain('grid-template-rows: minmax(0, 65fr) minmax(var(--space-8), 35fr)');
    expect(css).toContain('.secondary-pane-strip .pane.collapsed');
    expect(css).toContain('grid-template-rows: minmax(0, 1fr) var(--machine-rail-width)');
    expect(main).not.toContain('class="toolbar"');
    expect(main).not.toContain('class="machines"');
    expect(main).not.toContain('class="sessions"');
  });

  it("captures both legacy and relay pairing drafts before a background render replaces markup", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source.indexOf("if (captureDraft) capturePairingDraft();")).toBeLessThan(source.indexOf("app.innerHTML ="));
    expect(source).toContain("updatePairingDraft(pairingDraft, new FormData(form).entries()");
    for (const field of ["hubUrl", "machineLabel", "deviceLabel", "operatorLabel", "scopes"]) {
      expect(source).toContain(`pairingDraft.${field}`);
    }
  });

  it("lets unleased observers size panes but preserves controller-owned geometry", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain('machines.get(machineId)?.scopes.includes("pane-read")');
    expect(source).toContain("return !lease?.controller_label || lease.held_by_me");
    expect(source).toContain("if (becameGeometryOwner) resizeViewablePanes(machineId, session)");
    expect(source).toContain("if (canResizePanes(machineId, session)) sendControl");
    expect(source).toContain("{ ResizePane: { pane_id: pane.id, cols: surface.cols, rows: surface.rows } }");
  });

  it("turns a reachable revoked hub into a terminal auth stop", async () => {
    const source = await readFile(new URL("connection.ts", import.meta.url), "utf8");
    expect(source).toContain('new URL("/v1/health", this.machine.baseUrl)');
    expect(source).toContain('mode: "no-cors"');
    expect(source).toContain("const reachable = await this.hubIsReachable()");
    expect(source).toContain("if (reachable)");
    expect(source).toContain("this.desired = false");
    expect(source).toContain("this.eventAbort?.abort()");
    expect(source).toContain('this.transition("failed", "auth", { reason: detail, authFailure: kind })');
    expect(source).toContain("this.callbacks.onAuthFailure?.(kind, detail)");
  });

  it("bounds a terminal that opens but never sends its initial session state", async () => {
    vi.useFakeTimers();
    vi.stubGlobal("window", globalThis);
    vi.stubGlobal("fetch", vi.fn(async () => ({ status: 200, ok: true, json: async () => ({ ticket: "unused" }) })));
    class FakeWebSocket {
      static readonly OPEN = 1;
      static readonly CONNECTING = 0;
      static instances: FakeWebSocket[] = [];
      readyState = FakeWebSocket.CONNECTING;
      binaryType = "";
      onopen: (() => void) | null = null;
      onmessage: ((message: MessageEvent) => void) | null = null;
      onclose: ((event: CloseEvent) => void) | null = null;
      onerror: (() => void) | null = null;
      constructor() { FakeWebSocket.instances.push(this); }
      open(): void { this.readyState = FakeWebSocket.OPEN; this.onopen?.(); }
      close(): void { this.readyState = 3; this.onclose?.({ code: 1006 } as CloseEvent); }
      send(): void {}
    }
    vi.stubGlobal("WebSocket", FakeWebSocket);

    const { privateKey, publicKey } = await createDeviceKey();
    const machine = {
      id: "machine", label: "Machine", baseUrl: "https://hub.example", deviceId: "device",
      credentialId: "credential-id", credential: "opaque-credential", expiresAt: new Date(Date.now() + 60_000).toISOString(),
      scopes: ["pane-read"], publicKey, privateKey,
    } satisfies StoredMachine;
    const callbacks = {
      onState: vi.fn(), onAttachState: vi.fn(), onSessions: vi.fn(), onMachineEvent: vi.fn(),
      onSessionState: vi.fn(), onOutput: vi.fn(), onPaneKeyframe: vi.fn(), onSocketError: vi.fn(),
    } satisfies HubCallbacks;
    const supervisor = new HubConnectionSupervisor(machine, callbacks);
    (supervisor as unknown as { desired: boolean }).desired = true;

    await supervisor.attach("factory-a");
    FakeWebSocket.instances[0].open();
    await vi.advanceTimersByTimeAsync(3_000);

    expect(callbacks.onSocketError).toHaveBeenCalledWith(
      "factory-a",
      "Terminal attach opened but sent no session state within 3s. Retrying…",
    );
    expect(callbacks.onAttachState.mock.calls.map(([, state]) => [state.phase, state.stage])).toEqual([
      ["auth", "auth"],
      ["dialing", "dialing"],
      ["attaching", "attaching"],
      ["failed", "attaching"],
      ["backoff", "attaching"],
    ]);
    expect(new Set(callbacks.onAttachState.mock.calls.slice(0, -1).map(([, state]) => state.attachSince)).size).toBe(1);
    expect(supervisor.attachSnapshot("factory-a")?.phase).toBe("backoff");
    supervisor.stop();
  });

  it("turns connection failures into timed actions while retaining prior terminal frames", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    const styles = await readFile(new URL("styles.css", import.meta.url), "utf8");
    expect(source).toContain("const view = connectingView(snapshot, now)");
    expect(source).toContain('retry.textContent = "Retry"');
    expect(source).toContain('diagnose.textContent = "Diagnose"');
    expect(source).toContain("openConnectionLog(machineId)");
    expect(source).toContain("const view = disconnectedView(snapshot, now)");
    expect(source).toContain("Disconnected ${view.elapsedSeconds}s ago");
    expect(styles).toContain(".terminal-state");
    expect(styles).toContain(".terminal-connecting-step");
    expect(styles).toContain(".terminal-disconnected .terminal-mount { opacity: .4; }");
  });

  it("drives pane recovery from the selected session attach lifecycle", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("onAttachState: (session, state) =>");
    expect(source).toContain("attachStates.set(sessionKey(machine.id, session), state)");
    expect(source).toContain("connection.attachSnapshot(selectedSession) ?? connection.snapshot()");
    expect(source).toContain("connection.attachSnapshot(session) ?? connection.snapshot()");
    expect(source).toContain("const connectionSnapshot = terminalAttachSnapshot ?? machineConnectionSnapshot");
    expect(source).toContain("connections.get(machineId)?.attach(session)");
  });

  it("removes the connecting instruction when the terminal state arrives", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain('grid.querySelector(".empty")?.remove();');
  });

  it("requests an authoritative supervisor keyframe before lazily mounted workers", async () => {
    const [connection, main] = await Promise.all(["connection.ts", "main.ts"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    expect(connection.indexOf("this.requestPaneKeyframe(session, supervisor.id)")).toBeLessThan(
      connection.indexOf("this.callbacks.onSessionState(session, welcome.state, undefined, true)"),
    );
    expect(connection).not.toContain("welcome.scrollback, true");
    expect(main).toContain('const collapsedOnPhone = window.matchMedia("(max-width: 850px)").matches');
    expect(main.indexOf("if (collapsedOnPhone) continue;")).toBeLessThan(
      main.indexOf("requestPaneKeyframe(session, pane.id)"),
    );
  });

  it.each(["stop", "auth-block"] as const)("cancels a scheduled attach retry on %s", async (terminalAction) => {
    vi.useFakeTimers();
    vi.stubGlobal("window", globalThis);
    const fetchMock = vi.fn(async () => ({ status: 200, ok: true, json: async () => ({ ticket: "unused" }) }));
    vi.stubGlobal("fetch", fetchMock);
    const socketOpened = vi.fn();
    class FakeWebSocket {
      static readonly OPEN = 1;
      static readonly CONNECTING = 0;
      readonly readyState = FakeWebSocket.OPEN;
      binaryType = "";
      onopen: (() => void) | null = null;
      onmessage: ((message: MessageEvent) => void) | null = null;
      onclose: ((event: CloseEvent) => void) | null = null;
      onerror: (() => void) | null = null;
      constructor() { socketOpened(); }
      close(): void {}
      send(): void {}
    }
    vi.stubGlobal("WebSocket", FakeWebSocket);

    const { privateKey, publicKey } = await createDeviceKey();
    const machine = {
      id: "machine", label: "Machine", baseUrl: "https://hub.example", deviceId: "device",
      credentialId: "credential-id", credential: "opaque-credential", expiresAt: new Date(Date.now() + 60_000).toISOString(),
      scopes: ["pane-read"], publicKey, privateKey,
    } satisfies StoredMachine;
    const callbacks = {
      onState: vi.fn(), onSessions: vi.fn(), onMachineEvent: vi.fn(),
      onSessionState: vi.fn(), onOutput: vi.fn(), onPaneKeyframe: vi.fn(), onSocketError: vi.fn(),
    } satisfies HubCallbacks;
    const supervisor = new HubConnectionSupervisor(machine, callbacks);
    const internals = supervisor as unknown as {
      desired: boolean;
      scheduleAttach(session: string): void;
      blockAuthentication(detail: string, session?: string): void;
      attachRetryTimers: Map<string, number>;
      socketAttempts: Map<string, number>;
    };
    internals.desired = true;
    internals.scheduleAttach("factory-a");
    internals.scheduleAttach("factory-a");

    expect(vi.getTimerCount()).toBe(1);
    if (terminalAction === "stop") supervisor.stop();
    else internals.blockAuthentication("revoked", "factory-a");
    await vi.advanceTimersByTimeAsync(20_000);
    await supervisor.attach("factory-a");

    expect(internals.attachRetryTimers.size).toBe(0);
    expect(internals.socketAttempts.size).toBe(0);
    expect(fetchMock).not.toHaveBeenCalled();
    expect(socketOpened).not.toHaveBeenCalled();
  });
});
