import { createHash, webcrypto } from "node:crypto";
import { readFile } from "node:fs/promises";
import { afterEach, describe, expect, it, vi } from "vitest";
import { HubConnectionSupervisor, type HubCallbacks } from "./connection";
import { createDeviceKey, dpopHeaders } from "./dpop";
import { consumePairingFragment } from "./fragment";
import type { StoredMachine } from "./types";

Object.defineProperty(globalThis, "crypto", { value: webcrypto, configurable: true });

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllGlobals();
});

describe("binding Commander browser invariants", () => {
  it("H4-CATALOG-01 consumes pairing fragments synchronously and preserves no capability in the URL", () => {
    const token = "A".repeat(43);
    let replacement = "";
    const location = { hash: `#pair=${token}&hub=machine-1`, pathname: "/", search: "" } as Location;
    const history = { replaceState: (_: unknown, __: string, path: string) => { replacement = path; } } as unknown as History;
    expect(consumePairingFragment(location, history)).toEqual({ token, hubId: "machine-1" });
    expect(replacement).toBe("/");
    expect(replacement).not.toContain(token);
  });

  it("keeps the legacy Pair action disabled with an explanation while offering page-initiated pairing", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
    expect(source).toContain('pendingPairing ? "" : \'<p class="pairing-disabled-reason">Pair is disabled until you open a pairing URL generated by <code>cas hub pair</code> on the machine.</p>\'');
    expect(source).toContain('<button type="button" ${pendingPairing ? "" : "disabled"}>Pair</button>');
    expect(source).toContain('id="pair-create" type="button" class="primary"');
    expect(source).toContain('pairingCreateInFlight ? "Creating…" : "Create pairing code"');
    expect(source).toContain("const relayAction = relayOrigin");
    expect(html).toContain('name="cas-pairing-relay-origin" content="https://petra-stella-cloud.vercel.app"');
  });

  it("binds the browser fetch receiver at every pairing handoff", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).not.toMatch(/fetcher:\s*(?:window\.|globalThis\.)?fetch\s*[,}]/);
    expect(source).not.toMatch(/(?:acknowledgePairing|createPairingRequest|pollPairingRequest)\(\s*(?:window\.|globalThis\.)?fetch\s*,/);
  });

  it("H4-STORAGE-02 creates a non-extractable P-256 signing key and valid proof", async () => {
    const { privateKey, publicKey } = await createDeviceKey();
    expect(privateKey.extractable).toBe(false);
    await expect(crypto.subtle.exportKey("jwk", privateKey)).rejects.toThrow();
    const machine = {
      id: "machine", label: "Machine", baseUrl: "https://hub.example", deviceId: "device",
      credentialId: "credential-id", credential: "opaque-credential", expiresAt: new Date(Date.now() + 60_000).toISOString(),
      scopes: ["machine-read"], publicKey, privateKey,
    } satisfies StoredMachine;
    const headers = await dpopHeaders(machine, "GET", "/v1/machine");
    const [encodedHeader, encodedClaims, encodedSignature] = headers.DPoP.split(".");
    const decode = (value: string) => Buffer.from(value, "base64url");
    expect(JSON.parse(decode(encodedClaims).toString())).toMatchObject({ htm: "GET", htu: "/v1/machine" });
    const imported = await crypto.subtle.importKey("jwk", publicKey, { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
    expect(await crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, imported, decode(encodedSignature), new TextEncoder().encode(`${encodedHeader}.${encodedClaims}`))).toBe(true);
  });

  it("pins the green Ghostty WASM spike artifacts by integrity", async () => {
    const cases = [
      ["terminal/ghostty/vendor/ghostty-vt.wasm", "6b1df1a96d59adc26360c312924898dbc122f980c17a32eb1624e48795b83f7e"],
      ["terminal/ghostty/vendor/ghostty-write-pty.wasm", "75cb147e98ede3f85f3cd6236a30f6d12565b0b237e1d8db941f5f3e8ad3d903"],
    ];
    for (const [path, expected] of cases) {
      const bytes = await readFile(new URL(path, import.meta.url));
      expect(createHash("sha256").update(bytes).digest("hex")).toBe(expected);
    }
  });

  it("keeps long-lived credentials out of ambient browser storage and URL channels", async () => {
    const source = await Promise.all(["storage.ts", "main.ts", "dpop.ts"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    const joined = source.join("\n");
    for (const forbidden of ["local" + "Storage", "document.cookie", "serviceWorker.register", "caches.open"]) {
      expect(joined).not.toContain(forbidden);
    }
    expect(await readFile(new URL("storage.ts", import.meta.url), "utf8")).not.toContain("session" + "Storage");
    expect(joined).toContain("indexedDB.open");
  });

  it("feature-detects hub versions and keeps controls disabled on skew", async () => {
    const source = await Promise.all(["main.ts", "connection.ts"].map((path) => readFile(new URL(path, import.meta.url), "utf8")));
    const joined = source.join("\n");
    expect(joined).toContain('"/v1/machine"');
    expect(joined).toContain("Compatibility check unavailable");
    expect(joined).toContain('hubSupports(machineId, "daemon_attach")');
    expect(joined).toContain("unsupported controls are disabled");
  });

  it("targets interrupt at the explicitly selected pane rather than render order", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("selectedPanes.get(sessionKey(selected.id, selectedSession))");
    expect(source).toContain("{ InterruptPane: { pane_id: pane } }");
    expect(source).not.toContain("[...surfaces.keys()].find");
  });

  it("never caches an asynchronously-created terminal against a detached render", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("existingSurface.element !== mount || !existingSurface.element.isConnected");
    expect(source).toContain("!mount.isConnected || currentMount !== mount");
    expect(source).toContain("surface.dispose();");
  });

  it("preserves the active pane grid across lease and status renders", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("currentGrid?.dataset.sessionKey === terminalSessionKey");
    expect(source).toContain("replaceWith(preservedGrid)");
    expect(source).toContain("data-session-key");
  });

  it("captures both legacy and relay pairing drafts before a background render replaces markup", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source.indexOf("if (captureDraft) capturePairingDraft();")).toBeLessThan(source.indexOf("app.innerHTML ="));
    expect(source).toContain("updatePairingDraft(pairingDraft, new FormData(form).entries()");
    for (const field of ["hubUrl", "machineLabel", "deviceLabel", "operatorLabel", "scopes"]) {
      expect(source).toContain(`pairingDraft.${field}`);
    }
  });

  it("resends the live grid size when observer mode becomes controller mode", async () => {
    const source = await readFile(new URL("main.ts", import.meta.url), "utf8");
    expect(source).toContain("const becameController = state.held_by_me && !leases.get(key)?.held_by_me");
    expect(source).toContain("if (becameController) resizeControlledPanes(machineId, session)");
    expect(source).toContain("{ ResizePane: { pane_id: pane.id, cols: surface.cols, rows: surface.rows } }");
  });

  it("turns a reachable revoked hub into a terminal auth stop", async () => {
    const source = await readFile(new URL("connection.ts", import.meta.url), "utf8");
    expect(source).toContain('new URL("/v1/health", this.machine.baseUrl)');
    expect(source).toContain('mode: "no-cors"');
    expect(source).toContain("const reachable = await this.hubIsReachable()");
    expect(source).toContain("if (reachable)");
    expect(source).toContain("this.desired = false");
    expect(source).toContain("this.eventAbort?.abort()");
    expect(source).toContain('this.callbacks.onState("auth-blocked", detail)');
  });

  it.each(["stop", "auth-block"] as const)("cancels a scheduled attach retry on %s", async (terminalAction) => {
    vi.useFakeTimers();
    vi.stubGlobal("window", globalThis);
    const fetchMock = vi.fn(async () => ({ status: 200, ok: true, json: async () => ({ ticket: "unused" }) }));
    vi.stubGlobal("fetch", fetchMock);
    const socketOpened = vi.fn();
    class FakeWebSocket {
      static readonly OPEN = 1;
      static readonly CONNECTING = 0;
      readonly readyState = FakeWebSocket.OPEN;
      binaryType = "";
      onopen: (() => void) | null = null;
      onmessage: ((message: MessageEvent) => void) | null = null;
      onclose: ((event: CloseEvent) => void) | null = null;
      onerror: (() => void) | null = null;
      constructor() { socketOpened(); }
      close(): void {}
      send(): void {}
    }
    vi.stubGlobal("WebSocket", FakeWebSocket);

    const { privateKey, publicKey } = await createDeviceKey();
    const machine = {
      id: "machine", label: "Machine", baseUrl: "https://hub.example", deviceId: "device",
      credentialId: "credential-id", credential: "opaque-credential", expiresAt: new Date(Date.now() + 60_000).toISOString(),
      scopes: ["pane-read"], publicKey, privateKey,
    } satisfies StoredMachine;
    const callbacks = {
      onState: vi.fn(), onSessions: vi.fn(), onMachineEvent: vi.fn(),
      onSessionState: vi.fn(), onOutput: vi.fn(), onSocketError: vi.fn(),
    } satisfies HubCallbacks;
    const supervisor = new HubConnectionSupervisor(machine, callbacks);
    const internals = supervisor as unknown as {
      desired: boolean;
      scheduleAttach(session: string): void;
      blockAuthentication(detail: string, session?: string): void;
      attachRetryTimers: Map<string, number>;
      socketAttempts: Map<string, number>;
    };
    internals.desired = true;
    internals.scheduleAttach("factory-a");
    internals.scheduleAttach("factory-a");

    expect(vi.getTimerCount()).toBe(1);
    if (terminalAction === "stop") supervisor.stop();
    else internals.blockAuthentication("revoked", "factory-a");
    await vi.advanceTimersByTimeAsync(20_000);
    await supervisor.attach("factory-a");

    expect(internals.attachRetryTimers.size).toBe(0);
    expect(internals.socketAttempts.size).toBe(0);
    expect(fetchMock).not.toHaveBeenCalled();
    expect(socketOpened).not.toHaveBeenCalled();
  });
});
