#!/usr/bin/env bash
# Regenerate the shipped-builtin-reference history ledger (cas-0c0a).
#
# `sync_owned_reference` preserves any destination whose content does not match
# its recorded baseline, on the theory that it is a local customization. Files
# installed before the baseline ledger existed (Jul 2026) have no baseline at
# all, so pristine-but-old CAS content was misclassified as a local edit and
# skipped forever. This script embeds the SHA-256 of every *previously shipped*
# version of each builtin reference file so sync can tell "old CAS version"
# (safe to replace) apart from "someone edited this" (must preserve).
#
# Run after landing changes to any builtin reference file, and before cutting a
# release:
#
#   ./scripts/gen-builtin-reference-history.sh
#
# Output: cas-cli/src/builtins/reference-history.json (committed, embedded via
# include_str!).
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

out="cas-cli/src/builtins/reference-history.json"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Collect "<builtin path>\t<sha256>" for every revision of every reference file,
# in every harness flavour (claude sources live directly under builtins/,
# codex/grok under builtins/{codex,grok}/). Harness flavours share a builtin
# path on purpose: a destination holding another harness's shipped copy is
# still shipped CAS content, not a local edit.
: >"$tmp"
while IFS= read -r file; do
  builtin_path="${file#cas-cli/src/builtins/}"
  builtin_path="${builtin_path#codex/}"
  builtin_path="${builtin_path#grok/}"
  # `--raw` yields the post-image blob id per revision directly, so renamed
  # ancestors resolve without re-deriving the historical path.
  while IFS= read -r blob; do
    case "$blob" in
      0000000000000000000000000000000000000000) continue ;;  # deletion
    esac
    hash="$(git cat-file blob "$blob" 2>/dev/null | sha256sum | cut -d' ' -f1)"
    [ -n "$hash" ] || continue
    printf '%s\t%s\n' "$builtin_path" "$hash" >>"$tmp"
  done < <(git log --follow --raw --no-abbrev --format= -- "$file" | awk '/^:/ {print $4}')
done < <(git ls-files 'cas-cli/src/builtins/*references*')

sort -u "$tmp" | python3 -c '
import json, sys
files = {}
for line in sys.stdin:
    line = line.rstrip("\n")
    if not line:
        continue
    path, digest = line.split("\t")
    files.setdefault(path, set()).add(digest)
doc = {
    "version": 1,
    "comment": "Generated by scripts/gen-builtin-reference-history.sh - SHA-256 of every previously shipped version of each builtin reference file. Do not hand-edit.",
    "files": {p: sorted(h) for p, h in sorted(files.items())},
}
print(json.dumps(doc, indent=2))
' >"$out"

echo "wrote $out ($(wc -c <"$out") bytes)"
