#!/usr/bin/env python3
"""Opt-in real capped-runner proof; never part of the no-build CI script tier."""
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest


class RealLaneCompile(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="lane-real-")
        self.addCleanup(self.temp.cleanup)
        self.repo = Path(self.temp.name).resolve() / "supervisor with spaces"
        self.repo.mkdir()
        self.git("init", "-q", "-b", "target")
        self.git("config", "user.name", "Lane real fixture")
        self.git("config", "user.email", "lane@example.invalid")
        self.git("config", "commit.gpgsign", "false")
        (self.repo / ".gitignore").write_text("/.cas/\n/target/\n")
        (self.repo / "Cargo.toml").write_text(
            '[package]\nname="lane-fixture"\nversion="0.1.0"\nedition="2024"\n')
        (self.repo / "Cargo.lock").write_text(
            '# This file is automatically @generated by Cargo.\n'
            '# It is not intended for manual editing.\n'
            'version = 4\n\n[[package]]\nname = "lane-fixture"\nversion = "0.1.0"\n')
        (self.repo / "src").mkdir()
        (self.repo / "src/lib.rs").write_text("pub fn value() -> u8 { 1 }\n")
        self.git("add", ".")
        self.git("commit", "-qm", "base")
        self.base = self.git("rev-parse", "HEAD")
        self.root = self.repo / ".cas"
        (self.root / "worktrees").mkdir(parents=True)
        self.git("checkout", "-qb", "factory/source")
        (self.repo / "src/lib.rs").write_text("pub fn value() -> u8 { 2 }\n")
        self.git("add", "src/lib.rs")
        self.git("commit", "-qm", "source")
        self.source = self.git("rev-parse", "HEAD")
        self.env = dict(os.environ, CAS_LANE_CHECK_CAS=str(CAS))
        # Use the normal resource guard and inherited build throttle.
        self.env.pop("CAS_FACTORY_BUILD_GUARD", None)

    def git(self, *args):
        return subprocess.check_output(["git", "-C", str(self.repo), *args],
                                       stderr=subprocess.STDOUT, text=True).strip()

    def run_logged(self, name, command, cwd):
        result = subprocess.run(command, cwd=cwd, env=self.env, capture_output=True, text=True)
        (PROOF_DIR / (name + ".log")).write_text(result.stdout + result.stderr)
        print(f"{name}: exit={result.returncode}\n{result.stdout}{result.stderr}", flush=True)
        return result

    def prove(self, caller, name):
        result = self.run_logged(name, ["python3", str(SCRIPT), str(caller),
                                       self.base, self.source, "--prove"], caller)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("PASS lane compile:", result.stdout)
        records = list((self.repo / ".git/lane-compile").glob("*.json"))
        self.assertEqual(len(records), 1)
        proof = json.loads(records[0].read_text())
        self.assertEqual(proof["result"], "PASS")
        self.assertEqual(proof["targets"], ["--lib", "--tests"])
        self.assertEqual(proof["packages"], ["lane-fixture"])
        self.assertEqual(proof["capped_runner"], "cas factory worker-check")
        self.assertEqual(self.git("rev-parse", "target"), self.base)
        self.assertEqual(self.git("rev-parse", "factory/source"), self.source)
        self.assertEqual(self.git("status", "--porcelain"), "")
        self.assertNotIn("lane-compile-", self.git("worktree", "list", "--porcelain"))

    def test_prove_from_supervisor_checkout(self):
        self.prove(self.repo, "supervisor")

    def test_prove_from_worker_checkout(self):
        worker = self.root / "worktrees/worker-source"
        self.git("worktree", "add", "-q", "--detach", str(worker), self.source)
        self.prove(worker, "worker")

    def test_unowned_checkout_still_refused(self):
        command = [str(CAS), "factory", "worker-check", "--cas-root", str(self.root),
                   "--", "-p", "lane-fixture", "--lib"]
        result = self.run_logged("unowned", command, self.repo)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("requires an isolated worktree", result.stderr)
        nested = self.root / "worktrees/unowned/nested"
        self.git("worktree", "add", "-q", "--detach", str(nested), self.source)
        result = self.run_logged("nested-unowned", command, nested)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("target ownership requires a private worker checkout", result.stderr)
        self.assertFalse(list((self.root / "worker-checks").glob("*/*.json")))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cas", required=True, help="real installed Cassy capped runner")
    parser.add_argument("--script", type=Path, default=Path(__file__).with_name("check-lane-compile.py"))
    parser.add_argument("--proof-dir", type=Path, required=True)
    args = parser.parse_args()
    CAS = Path(shutil.which(args.cas) or args.cas).resolve()
    SCRIPT = args.script.resolve()
    PROOF_DIR = args.proof_dir.resolve()
    PROOF_DIR.mkdir(parents=True, exist_ok=True)
    unittest.main(argv=[__file__])
