//! Turning a routed legacy row into a `knowledge_pages` row + markdown body.
//!
//! Three things here are load-bearing and each has a test:
//!
//! 1. **`rel_path` carries a legacy-id suffix.** `canonical_rel_path` derives
//!    the path from `page_type` + `title` and the column has a UNIQUE index, so
//!    two legacy rows with the same type and title resolve to the same path and
//!    the second would `ON CONFLICT(rel_path) DO UPDATE` straight over the
//!    first. Only 641 of 1696 rows have a title; the rest fall back to
//!    `preview(60)`, which collides far more readily. Suffixing every migrated
//!    page with its legacy short id makes the collision structurally impossible
//!    instead of statistically unlikely — a distinct memory silently
//!    overwriting another is exactly the loss this epic exists to prevent.
//! 2. **The locked bit is applied after `commit_ingest`.** `commit_ingest`
//!    never touches `locked` on an update and guards the update with
//!    `WHERE knowledge_pages.locked = 0` (`knowledge_store.rs:938`), so Rule L1
//!    needs the same unlock → write → re-lock dance the hand-written-page path
//!    uses (`mcp/tools/core/knowledge.rs:289-377`). Without the re-lock, AC4
//!    fails *silently*; without the unlock, a resumed run wedges forever on a
//!    page it locked before the crash.
//! 3. **`sources_json` is empty** (Rule P2). `sources` is CAS-owned and
//!    regenerated by distillation; a synthetic path would be overwritten on the
//!    next pass and would corrupt the source ledger. Origin lives in
//!    `cas_legacy_id` / `cas_legacy_db` instead. An empty source list is safe
//!    here because the cascade delete only reaches pages that *cite* a
//!    tombstoned path (`pages_for_source`), and a page with no sources is
//!    cited by nothing.

use anyhow::{Context, Result, bail};
use cas_store::{IngestBatch, KnowledgePage, KnowledgeStore, PageWrite, canonical_rel_path};
use chrono::{DateTime, TimeZone, Utc};
use sha2::{Digest, Sha256};

use super::DbLabel;
use super::frontmatter;
use super::routing::Disposition;
use super::source::LegacyRow;

/// Longest snippet injected into the index block.
const SNIPPET_CHARS: usize = 200;

/// `entries.type` → `knowledge_pages.page_type` (§4.2).
pub fn page_type_for(entry_type: &str) -> &'static str {
    match entry_type {
        "context" => "context",
        "preference" => "persona",
        "observation" => "observation",
        _ => "learning",
    }
}

/// Stable per-row token: the same legacy row always yields the same page id and
/// the same `rel_path`, which is what makes both idempotence (AC2) and resume
/// (AC3) work without consulting run history.
pub fn short_id(db: DbLabel, legacy_id: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(db.as_str().as_bytes());
    hasher.update([0x1f]);
    hasher.update(legacy_id.as_bytes());
    hex(&hasher.finalize()[..5])
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

pub fn page_id(db: DbLabel, legacy_id: &str) -> String {
    format!("cas-kn-mig-{}", short_id(db, legacy_id))
}

/// Canonical path plus the legacy-id suffix that makes collisions impossible.
pub fn rel_path_for(row: &LegacyRow, db: DbLabel) -> String {
    let canonical = canonical_rel_path(page_type_for(&row.entry_type), &row.display_title());
    let stem = canonical.strip_suffix(".md").unwrap_or(&canonical);
    format!("{stem}-{}.md", short_id(db, &row.id))
}

fn snippet_of(content: &str) -> String {
    let flat = content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with("---"))
        .collect::<Vec<_>>()
        .join(" ");
    let first = match flat.find(". ") {
        Some(index) => &flat[..index + 1],
        None => flat.as_str(),
    };
    super::source::preview(first, SNIPPET_CHARS)
}

/// Legacy timestamps are RFC3339 in practice but the column is free text, so a
/// junk value must not abort a migration over one bad row — it falls back to
/// the epoch, and the *verbatim* value still rides in `cas_legacy_created`.
fn parse_ts(value: &str) -> DateTime<Utc> {
    DateTime::parse_from_rfc3339(value)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(|_| Utc.timestamp_opt(0, 0).single().unwrap_or_default())
}

/// Compose the markdown body: rendered frontmatter immediately followed by the
/// legacy content, byte for byte.
///
/// There is deliberately no blank line between the closing `---` and the
/// content: [`body_after_frontmatter`] must be able to hand back the original
/// bytes exactly for AC4.
pub fn compose_body(row: &LegacyRow, db: DbLabel, title: &str, locked: bool) -> String {
    let meta = crate::knowledge::merge::Frontmatter {
        title: title.to_string(),
        page_type: page_type_for(&row.entry_type).to_string(),
        sources: Vec::new(),
        locked,
        updated: row.updated_at.clone().or_else(|| Some(row.created.clone())),
        passthrough: frontmatter::legacy_lines(row, db),
    };
    let mut body = crate::knowledge::merge::render_frontmatter(&meta);
    body.push_str(&row.content);
    body
}

/// The exact bytes that were carried, i.e. everything after the frontmatter's
/// closing `---` line. Used by the byte-identity assertion for AC4.
///
/// Not `split_frontmatter`: that helper trims leading newlines off the
/// remainder, which would make a body starting with a blank line compare equal
/// to one that does not.
pub fn body_after_frontmatter(body: &str) -> &str {
    let Some(rest) = body.strip_prefix("---\n") else {
        return body;
    };
    let mut offset = 0usize;
    for line in rest.split_inclusive('\n') {
        if line.trim_end() == "---" {
            return &rest[offset + line.len()..];
        }
        offset += line.len();
    }
    body
}

/// A row prepared for writing.
pub struct PreparedPage {
    pub page: KnowledgePage,
    pub body: String,
    pub locked: bool,
}

pub fn prepare(row: &LegacyRow, db: DbLabel, disposition: Disposition) -> PreparedPage {
    let locked = disposition == Disposition::CarryVerbatim;
    let title = row.display_title();
    let created = parse_ts(&row.created);
    let updated = row.updated_at.as_deref().map(parse_ts).unwrap_or(created);

    let mut page = KnowledgePage::new(
        page_id(db, &row.id),
        page_type_for(&row.entry_type),
        title.clone(),
    );
    page.rel_path = rel_path_for(row, db);
    page.snippet = snippet_of(&row.content);
    page.sources = Vec::new(); // Rule P2
    page.locked = locked; // honoured on INSERT; Rule L1 re-asserts it after
    page.created_at = created; // Rule P1 — native column *and* frontmatter
    page.updated_at = updated;
    page.pending_embedding = true;

    PreparedPage {
        page,
        body: compose_body(row, db, &title, locked),
        locked,
    }
}

/// Write one prepared page, honouring the lock protocol in both directions.
///
/// Returns the id the page ended up under.
pub fn write_page(store: &dyn KnowledgeStore, prepared: &PreparedPage) -> Result<String> {
    let existing = store
        .get_page_by_rel_path(&prepared.page.rel_path)
        .with_context(|| format!("looking up {}", prepared.page.rel_path))?;
    // Reuse the id already at this path. `commit_ingest`'s ON CONFLICT is on
    // `rel_path`, so it would keep the old id and our `set_locked` would then
    // aim at a page that does not exist.
    let id = existing
        .as_ref()
        .map(|page| page.id.clone())
        .unwrap_or_else(|| prepared.page.id.clone());
    let was_locked = existing.as_ref().is_some_and(|page| page.locked);

    if was_locked {
        // Resume path: the previous run locked this page and then died before
        // its ledger line was flushed. Without this, `commit_ingest` writes
        // nothing (`WHERE locked = 0`) and the run can never converge.
        store
            .set_locked(&id, false)
            .with_context(|| format!("unlocking {id} for rewrite"))?;
    }

    let mut page = prepared.page.clone();
    page.id = id.clone();

    let batch = IngestBatch {
        pages: vec![PageWrite {
            page,
            body: prepared.body.clone(),
        }],
        ..IngestBatch::default()
    };

    let report = match store.commit_ingest(&batch) {
        Ok(report) => report,
        Err(e) => {
            if was_locked {
                let _ = store.set_locked(&id, true); // leave it as we found it
            }
            return Err(anyhow::Error::new(e))
                .with_context(|| format!("writing page {}", prepared.page.rel_path));
        }
    };
    if report.pages_written == 0 {
        if was_locked {
            let _ = store.set_locked(&id, true);
        }
        bail!(
            "destination page {} is locked by someone other than this migration; \
             unlock it or remove it before re-running (migration will not overwrite \
             a user-owned page)",
            prepared.page.rel_path
        );
    }

    if prepared.locked {
        // Rule L1 — carry-verbatim pages must end locked, and §11 assert 8 says
        // to verify it rather than trust the write.
        store
            .set_locked(&id, true)
            .with_context(|| format!("locking carry-verbatim page {id}"))?;
        let confirmed = store
            .get_page(&id)
            .with_context(|| format!("re-reading {id} to confirm the lock"))?;
        if !confirmed.locked {
            bail!(
                "carry-verbatim page {} did not end the run locked (Rule L1 / §11 assert 8)",
                prepared.page.rel_path
            );
        }
    }

    Ok(id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn colliding_titles_get_distinct_paths() {
        let a = LegacyRow::for_test("p-a", "context", Some("Same Title"), "one");
        let b = LegacyRow::for_test("p-b", "context", Some("Same Title"), "two");
        assert_ne!(
            rel_path_for(&a, DbLabel::Project),
            rel_path_for(&b, DbLabel::Project)
        );
    }

    #[test]
    fn the_same_row_always_yields_the_same_path_and_id() {
        let row = LegacyRow::for_test("p-a", "context", Some("Stable"), "one");
        assert_eq!(
            rel_path_for(&row, DbLabel::Project),
            rel_path_for(&row, DbLabel::Project)
        );
        assert_eq!(
            page_id(DbLabel::Project, "p-a"),
            page_id(DbLabel::Project, "p-a")
        );
        // Same legacy id in the two databases must not collide.
        assert_ne!(
            page_id(DbLabel::Project, "x"),
            page_id(DbLabel::Global, "x")
        );
    }

    #[test]
    fn preferences_become_persona_pages() {
        assert_eq!(page_type_for("preference"), "persona");
        assert_eq!(page_type_for("context"), "context");
        assert_eq!(page_type_for("learning"), "learning");
    }

    #[test]
    fn an_untitled_row_falls_back_to_a_preview_path() {
        let row = LegacyRow::for_test("p-a", "context", None, "the hooks live in cas-core");
        let path = rel_path_for(&row, DbLabel::Project);
        assert!(
            path.starts_with("context/the-hooks-live-in-cas-core-"),
            "{path}"
        );
        assert!(path.ends_with(".md"));
    }

    #[test]
    fn body_round_trips_byte_identically() {
        for content in [
            "plain",
            "with a\n---\nseparator inside\n",
            "\n\nleading blank lines",
            "trailing newline\n",
            "",
        ] {
            let row = LegacyRow::for_test("p-a", "context", Some("T"), content);
            let body = compose_body(&row, DbLabel::Project, "T", false);
            assert_eq!(
                body_after_frontmatter(&body),
                content,
                "failed for {content:?}"
            );
        }
    }

    #[test]
    fn a_locked_body_asserts_the_lock_bit_in_its_frontmatter() {
        let row = LegacyRow::for_test("p-a", "preference", Some("T"), "x");
        let body = compose_body(&row, DbLabel::Project, "T", true);
        assert!(body.contains("locked: true"));
        assert!(crate::knowledge::merge::is_locked_body(&body));
    }

    #[test]
    fn an_unparseable_timestamp_does_not_abort_the_row() {
        let mut row = LegacyRow::for_test("p-a", "context", Some("T"), "x");
        row.created = "not a date".to_string();
        let prepared = prepare(&row, DbLabel::Project, Disposition::MigrateToPage);
        assert_eq!(prepared.page.created_at.timestamp(), 0);
        // The original string still rides verbatim.
        assert!(prepared.body.contains("cas_legacy_created: not a date"));
    }

    #[test]
    fn snippets_stop_at_the_first_sentence_and_skip_rule_lines() {
        assert_eq!(snippet_of("First one. Second one."), "First one.");
        assert_eq!(snippet_of("---\nAfter the rule"), "After the rule");
        assert!(snippet_of(&"x".repeat(500)).chars().count() <= SNIPPET_CHARS);
    }

    #[test]
    fn prepared_pages_never_claim_a_source_path() {
        let row = LegacyRow::for_test("p-a", "context", Some("T"), "x");
        let prepared = prepare(&row, DbLabel::Project, Disposition::MigrateToPage);
        assert!(prepared.page.sources.is_empty(), "Rule P2");
        assert!(!prepared.locked, "Rule L2 — migrate-to-page stays unlocked");
    }
}
